services:

  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    container_name: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_NODENAME: rabbit@rabbit1
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    container_name: rabbit2
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_NODENAME: rabbit@rabbit2
    depends_on:
      - rabbit1

  rabbit3:
    image: rabbitmq:3-management
    hostname: rabbit3
    container_name: rabbit3
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_NODENAME: rabbit@rabbit3
    depends_on:
      - rabbit1